# Generated by Django 4.0.4 on 2022-05-02 10:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Введите регион', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название РП', max_length=200)),
                ('code', models.CharField(help_text='Введите код РП', max_length=8)),
                ('webhook', models.CharField(blank=True, help_text='Введите вебхук Б24', max_length=100, validators=[django.core.validators.URLValidator(message='Введите вебхук в формате: https://ds2016.bitrix24.ru/rest/589/bqm4wp9vy3eatlfn/')])),
                ('responsible', models.PositiveIntegerField(blank=True, help_text='ID ответственного сотрудника в Б24')),
                ('region', models.ManyToManyField(help_text='Выберите регион', to='b24.region')),
            ],
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('partner', models.ForeignKey(help_text='Выберите партнёра', null=True, on_delete=django.db.models.deletion.SET_NULL, to='b24.partner')),
                ('region', models.ForeignKey(help_text='Выберите регион', null=True, on_delete=django.db.models.deletion.SET_NULL, to='b24.region')),
            ],
        ),
    ]
