# Generated by Django 4.0.4 on 2022-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='responsible',
            field=models.PositiveIntegerField(blank=True, help_text='ID ответственного сотрудника в Б24', null=True),
        ),
    ]
