# Generated by Django 4.0.4 on 2022-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24', '0002_alter_partner_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(default=13, max_length=254),
            preserve_default=False,
        ),
    ]
