# Generated by Django 4.0.4 on 2022-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24', '0004_demorequest_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='is_verified',
            field=models.BooleanField(null=True),
        ),
    ]
