# Generated by Django 4.0.4 on 2022-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24', '0005_alter_demorequest_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='verification_code',
            field=models.BigIntegerField(max_length=4, null=True),
        ),
    ]
